// <auto-generated />
namespace SatelliteTec.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class State : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(State));
        
        string IMigrationMetadata.Id
        {
            get { return "202006032040034_State"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
